describe('params specs', function ()
  it('can be created', function ()
    pending('Test not implemented') 
  end)
  it('can be added', function ()
    pending('Test not implemented')
  end)
  it('can index variables in params', function ()
    pending('Test not implemented')    
  end)
  it('can index variables in params when combined', function ()
    pending('Test not implemented')
  end)
  it('can check if all the variables in params are resolved', function ()
    pending('Test not implemented')
  end)
  it('can check if all the variables in params are resolved when combined', function ()
    pending('Test not implemented')
  end)
  it('can resolve variables in params', function ()
    pending('Test not implemented')
  end)
  it('can resolve variables in params when combined', function ()
    pending('Test not implemented')
  end)
end)

